name: ARC Docker Build Test

on:
  workflow_dispatch:

jobs:

  docker-test:
    runs-on: arc-runner-set

    steps:

      # ======================================================
      # 1. Checkout
      # ======================================================

      - name: Checkout Repository
        uses: actions/checkout@v4


      # ======================================================
      # 2. Runner Information
      # ======================================================

      - name: Runner Information
        run: |
          echo "======================================"
          echo "ARC Runner"
          echo "======================================"

          echo "Runner Name:"
          echo "${RUNNER_NAME}"

          echo ""

          echo "Hostname:"
          hostname

          echo ""

          echo "Architecture:"
          uname -m


      # ======================================================
      # 3. Docker Information
      # ======================================================

      - name: Docker Information
        run: |
          echo "======================================"
          echo "Docker"
          echo "======================================"

          docker version

          echo ""

          docker info


      # ======================================================
      # 4. Build Test Image
      # ======================================================

      - name: Build Docker Image
        run: |
          echo "======================================"
          echo "Docker Build"
          echo "======================================"

          docker build \
            -t devops-roadmap:test \
            .


      # ======================================================
      # 5. Check Image
      # ======================================================

      - name: Check Docker Image
        run: |
          echo "======================================"
          echo "Docker Images"
          echo "======================================"

          docker images

          echo ""

          docker image inspect devops-roadmap:test


      # ======================================================
      # 6. Finish
      # ======================================================

      - name: Finish
        run: |
          echo "======================================"
          echo "Docker Build Successful"
          echo "======================================"